FORMAT: 0.01 BETA
HOST: http://app.chargeback.com/

# Chargeback API

The Chargeback API is a collection of RESTful JSON calls. The API uses standardized HTTP verbs and resource routes. Whenever possible, all JSON results will use a standardized format.

Depending on the access controls granted to the key authorizing the request, some actions may be unavailable.

## Standardized HTTP verbs and routes

Assuming the "orders" resource, the following routes are available:

| Verb | Action | Route             | Purpose                                                                             |
|------|--------|-------------------|-------------------------------------------------------------------------------------|
| GET  | search | /orders.json      | Search existing orders (see Orders section for search keys and return values)       |
|      | show   | /orders/(id).json | Retrieve information about a single order                                           |
| POST | create | /orders.json      | Create a new order.                                                                 |
| PUT  | update | /orders/(id).json | Update an existing order with new information                                       |
| POST | submit | /orders.json      | For convenience, a shortcut method to update or create based on unique identifiers. |

For all "search" operations, no more than 100 records will be returned at a time. The "page" parameter controls which page is returned. If more data exists, the search results will include the link for the subsequent page.

Show, create, update, and submit should return a JSON object that represents the resource. Search will return an array of such JSON objects.

## Authentication

The Chargeback API uses HTTP Basic Authentication. Your credentials to use the web application can have API access enabled, and the same resources will be available.

## Group Order Collection

Create and search Orders.

## Order [/orders.json]

A Order object represents a single sales order in the ecommerce platform, POS system, or sales platform for the merchant. It has the following attributes:

| Key                        | Type               | Importance  | Purpose                                                                                                                                  |
|----------------------------|--------------------|-------------|------------------------------------------------------------------------------------------------------------------------------------------|
| order_id                   | string             | REQUIRED    | The merchant system's unique identifier for the order                                                                                    |
| order_ts                   | ISO 8601           | REQUIRED    | The merchant system's "order completed" timestamp                                                                                        |
| order_amount               | decimal            | REQUIRED    | The final total amount of the order                                                                                                      |
| transaction_id             | string             | REQUIRED    | The transaction id in the payment gateway for the credit card transaction                                                                |
| transaction_amount         | decimal            | REQUIRED    | The amount charged in the payment gateway for the credit card transaction.                                                               |
| crm_id, crm_name           | integer / string   | REQUIRED    | Chargeback's identifier for the data source, or the name of the data source (agreed upon beforehand)                                     |
| merchant_id, merchant_name | integer / string   | REQUIRED    | Chargeback's identifier for the merchant, or the name of the merchant.                                                                   |
| card_prefix                | 6 numerical digits | RECOMMENDED | The first six digits of the card number. Alternatively, use the card_number field.                                                       |
| card_suffix                | 4 numerical digits | RECOMMENDED | The last four digits of the card number. Alternatively, use the card_number field.                                                       |
| card_number                | 13-16 char. string |             | If you use this field, you must pass the PAN in a masked format. Chargeback will extract the prefix and suffix.                          |
| card_type                  | string             | (derived)   | The card network of the card used in the transaction. If not passed, Chargeback will ascertain based on card #                           |
| card_exp                   | MM/YY              | RECOMMENDED | The expiration date captured at time of sale                                                                                             |
| reported_avs_status        | string             | RECOMMENDED | If captured, the AVS status of the transaction                                                                                           |
| reported_cvv_status        | string             | RECOMMENDED | If captured, the CVV status of the transaction                                                                                           |
| currency_code              | ISO 4217 (string)  |             | Defaults to USD                                                                                                                          |
| ip_address                 | dotted quad        | RECOMMENDED | The IP used by the cardholder to place the order in the merchant's sales platform. Will be compared with billing and shipping addresses. |
| authorization_code         | string             | RECOMMENDED | If captured, the authorization code returned by the gateway                                                                              |
| arn                        | string             | RECOMMENDED | The ARN, if known                                                                                                                        |
| shipping_subtotal          | decimal            |             | The amount charged for shipping.                                                                                                         |
| tax_subtotal               | decimal            |             | The amount charged for tax                                                                                                               |
| source_url                 | string             |             | The url to access this order in the merchant's sales platform.                                                                           |
|                            |                    |             |                                                                                                                                          |
| tracking_numbers           | comma list         | RECOMMENDED | Comma-separated list of tracking numbers; each will generate new shipment objects. See shipment actions.                                 |
|                            |                    |             |                                                                                                                                          |
| line_items[]               |                    |             | The line items on the order; the products that were actually sold. line_items should be an array of json objects.                        |
| - product_name             |                    |             | The name of the product sold, as it stood at the time of the order.                                                                      |
| - product_description      |                    |             | The description of the product, as it stood at the time of the order.                                                                    |
| - product_amount           | decimal            |             | The price of the product at the time of the order.                                                                                       |
| - quantity                 | integer            |             | The number of this line item sold.                                                                                                       |
| - subtotal                 | decimal            |             | Should be equal to quantity * subtotal. Can be computed from these if left blank.                                                        |
| - source_product_id        | string             |             | The unique identifier of the product in the source system's backend database                                                             |
|                            |                    |             |                                                                                                                                          |
| [ CUSTOMER PROFILE ]       |                    |             | If the customer is a registered user in your system, pass the customer profile information                                               |
| customer_email             | string             |             |                                                                                                                                          |
| customer_last_name         | string             |             |                                                                                                                                          |
| customer_first_name        | string             |             |                                                                                                                                          |
| customer_phone             | string             |             |                                                                                                                                          |
|                            |                    |             |                                                                                                                                          |
| [ BILLING INFO ]           |                    |             | The billing information captured for this particular transaction                                                                         |
| billing_last_name          |                    |             |                                                                                                                                          |
| billing_first_name         |                    |             |                                                                                                                                          |
| billing_address1           |                    |             |                                                                                                                                          |
| billing_address2           |                    |             |                                                                                                                                          |
| billing_city               |                    |             |                                                                                                                                          |
| billing_state              |                    |             |                                                                                                                                          |
| billing_country            |                    |             |                                                                                                                                          |
| billing_postal             |                    |             |                                                                                                                                          |
|                            |                    |             |                                                                                                                                          |
| [ SYSTEM FIELDS ]          |                    |             | These fields are either computed, derived, or stored internally by chargeback, but may prove useful to some merchants.                   |
| id                         | integer            |             | Chargeback's unique identifier for this order (maybe be used for updates)                                                                |
| avs_status                 | string             |             | Normalized version of the reported_avs_status, if recognized                                                                             |
| cvv_status                 | string             |             | Normalized version of the reported_cvv_status, if recognized                                                                             |
| created_at                 | ISO 8601           |             | The time in UTC when the order record was originally added to the database                                                               |
| updated_at                 | ISO 8601           |             | The last time in UTC when the order record was modified                                                                                  |
| creator_id                 | integer            |             | The id of the creator of the record. For API calls, it will be the user record that authorized the call                                  |
| creator_type               | string             |             | The type of creator of the record. For API calls, it will be the string 'User'                                                           |
| manually_generated         | boolean            |             | This will only be set to true for records created in the web UI                                                                          |
|                            |                    |             |                                                                                                                                          |
| [ FUTURE SUPPORT ]         |                    |             | Don't use these fields yet, as they are not supported by this version of the API.                                                        |
| canceled_ts                | ISO 8601           |             | If the order is canceled, pass this timestamp in an update call                                                                          |
| refund_amount              | decimal            |             | If the order is refunded, pass this amount in an update call                                                                             |
| refund_transaction_id      | string             |             | The payment gateway transaction id for the refund, passed in an update call                                                              |
| full_refund_ts             | ISO 8601           |             | The timestamp an order's refund was issued                                                                                               |
| partial_refund_ts          | ISO 8601           |             | The timestamp a partial refund was issued                                                                                                |
| rma                        | string             |             | The return merchandise authorization code used in a return                                                                               |

### Create a New Order [POST]

You may report a completed Order using this action. It takes a JSON object.

+ Request (application/json)

        {
            'crm_id : 444,
            'merchant_id' : 12345,
            'order_id' : 'abc123',
            'order_ts' : '2017-11-27T23:59:26Z'
            'order_amount' : '177.16',
            'transaction_id' : 'qwertyzzz',
            'transaction_amount' : '55.00',
            'card_prefix' : '444321',
            'card_suffix' : '8215',
            'card_exp' : '05/21',
            'reported_avs_status' : 'Y',
            'reported_cvv_status' : 'M',
            'ip_address' : '172.98.44.123',
            'authorization_code' : 'xxyyzz',
            'shipping_subtotal' : '5.00',
            'tax_subtotal' : '5.00',
            'source_url' : 'https://my-magento-site.com/admin-area/order-search.php?order_id=abc123',
            'tracking_numbers' : '1ZY2F2150255600110',
            'line_items' : [
                {
                    'product_name' : 'MIRRORLESS MICRO FOUR THIRDS 45-150 MM',
                    'product_description' : 'PANASONIC LUMIX G VARIO LENS, 45-150MM, F4.0-5.6 ASPH., MIRRORLESS MICRO FOUR THIRDS, MEGA OPTICAL I.S., H-FS45150AK (USA BLACK)',
                    'product_amount' : '147.99',
                    'quantity' : 1,
                    'subtotal' : '147.99',
                    'source_product_id' : 'prod-123'
                },
                {
                    'product_name' : 'Lens Cap',
                    'product_description' : 'Lens cap with lanyard fits most panasonic lumix cameras',
                    'product_amount' : '5.99',
                    'quantity' : 2,
                    'subtotal' : '11.98',
                    'source_product_id' : 'prod-777'
                }
            ],
            'shipping_subtotal' : '5.99',
            'tax_subtotal' : '11.20',
            'billing_first_name' : 'Nate',
            'billing_last_name' : 'Smith',
            'billing_address1' : '12345 My Actual House',
            'billing_city' : 'South Jordan',
            'billing_state' : 'UT',
            'billing_country' : 'USA',
            'billing_postal' : '84009',
        }

+ Response 201 (application/json)

    + Headers

            Location: orders/12345678.json

    + Body
            {
                'id' : '12345678',
                'avs_status' : 'Y',
                'cvv_status' : 'M',
                'created_at' : '2017-11-28T00:01:42Z',
                'updated_at' : '2017-11-28T00:01:42Z',
                'creator_id' : '55555',
                'creator_type' : 'User',
                'manually_generated' : false,
                'shipments' : [
                    {
                        'tracking_number' : '1ZY2F2150255600110',
                        'tracking_summary': null,
                        'shipper_name' : 'UPS',
                        'shipped_ts' : null,
                        'origin_name' : 'Cameras R Us',
                        'origin_address1' : '555 A Texas Road',
                        'origin_city' : 'Austin',
                        'origin_state' : 'TX',
                        'origin_country' : 'USA',
                        'origin_zip' : '73301',
                        'destination_first_name' : 'Nate'
                        'destination_last_name' : 'Smith',
                        'destination_address1' : '10235 S. Jordan Gateway',
                        'destination_address2' : 'Suite 500',
                        'destination_city' : 'South Jordan',
                        'destination_state' : 'UT',
                        'destination_country' : 'USA',
                        'destination_zip' : '84095',
                    }
                ],
                'crm_id' : 444,
                'merchant_id' : 12345,
                'order_id' : 'abc123',
                'order_ts' : '2017-11-27T23:59:26Z'
                'order_amount' : '177.16',
                'transaction_id' : 'qwertyzzz',
                'transaction_amount' : '55.00',
                'card_prefix' : '444321',
                'card_suffix' : '8215',
                'card_exp' : '05/21',
                'reported_avs_status' : 'Y',
                'reported_cvv_status' : 'M',
                'ip_address' : '172.98.44.123',
                'authorization_code' : 'xxyyzz',
                'shipping_subtotal' : '5.00',
                'tax_subtotal' : '5.00',
                'source_url' : 'https://my-magento-site.com/admin-area/order-search.php?order_id=abc123',
                'tracking_numbers' : '1ZY2F2150255600110',
                'line_items' : [
                    {
                        'product_name' : 'MIRRORLESS MICRO FOUR THIRDS 45-150 MM',
                        'product_description' : 'PANASONIC LUMIX G VARIO LENS, 45-150MM, F4.0-5.6 ASPH., MIRRORLESS MICRO FOUR THIRDS, MEGA OPTICAL I.S., H-FS45150AK (USA BLACK)',
                        'product_amount' : '147.99',
                        'quantity' : 1,
                        'subtotal' : '147.99',
                        'source_product_id' : 'prod-123'
                    },
                    {
                        'product_name' : 'Lens Cap',
                        'product_description' : 'Lens cap with lanyard fits most panasonic lumix cameras',
                        'product_amount' : '5.99',
                        'quantity' : 2,
                        'subtotal' : '11.98',
                        'source_product_id' : 'prod-777'
                    }
                ],
                'shipping_subtotal' : '5.99',
                'tax_subtotal' : '11.20',
                'billing_first_name' : 'Nate',
                'billing_last_name' : 'Smith',
                'billing_address1' : '12345 My Actual House',
                'billing_city' : 'South Jordan',
                'billing_state' : 'UT',
                'billing_country' : 'USA',
                'billing_postal' : '84009',
            }

### Search / List Orders [GET]

You may search existing orders that your api user is authorized to view.

TODO: More information here about search keys, pagination, and some request / response examples.


## Group Single Order

View and update single orders

## Order [/orders/12345678.json]

### Show an existing Order [GET]

You may view an existing Order record and its details.

### Update an existing Order [PUT]

You may update information about an Order already reported to Chargeback using this action. You must specify the Order based on Chargeback's unique identifier (id) for the Order.

+ Request (application/json)
    {
        'id' : 12345678,
        'billing_address1' : '12345 a different address',
        'billing_city' : 'Another City',
        'billing_state' : 'CA',
        'billing_country' : 'USA',
        'billing_postal' : '90233'
    }
+ Response 201 (application/json)

    + Headers

            Location: orders/12345678.json

    + Body
        {
            'id' : '12345678',
            'etc' : '...'
        }
### Submit (create or update) an Order [PUT]

You may create or update orders based on the unique identifiers (crm_id, merchant_id, order_id) of the order. If such a record already exists, it will be updated. Otherwise, a new record will be created.

+ Request (application/json)
    {
        'crm_id' : 777,
        'merchant_id' : 8888,
        'order_id' : 'abcdef54321',
        'etc': '...'
    }
+ Response 201 (application/json)

    + Headers

            Location: orders/55555.json

    + Body
        {
            'id' : 55555,
            'etc' : '...'
        }
## Group Transactions

## Transaction [/transactions.json]

A Transaction object represents a single credit card transaction in the payment gateway.

## Group Disputes

## Dispute [/disputes.json]

A Dispute is a retrieval request, chargeback, or pre_arbitration / second chargeback reported by the payment processor.

## Group Alerts

## Alert [/alerts.json]

An Alert notifies of a pending chargeback.

## Group Mids

## Mid [/mids.json]

The MID, or Merchant ID, is an identifier for the merchant account. Since larger merchants often use many MIDs, you can use the MID endpoints to keep Chargeback up-to-date with the MIDs you are using.
