FORMAT: 0.01 BETA
HOST: http://app.chargeback.com/

# Chargeback API

The Chargeback API is a collection of RESTful JSON calls. The API uses standardized HTTP verbs and resource routes. Whenever possible, all JSON results will use a standardized format.

Depending on the access controls granted to the key authorizing the request, some actions may be unavailable.

## Authentication

The Chargeback API uses HTTP Basic Authentication. Your credentials to use the web application can have API access enabled, and the same resources will be available.

## Group Order Collection

Create and search Orders.

## Order [/orders.json]

A Order object represents a single sales order in the ecommerce platform, POS system, or sales platform for the merchant. It has the following attributes:

+ crm_id - Chargeback's unique identifier for a data source that acts as sales platform
+ merchant_id - Chargeback's unique identifier for the merchant
+ order_id - The remote system's unique identifier for the order
+ order_ts - The remote system's "order completed" timestamp in ISO 8601 UTC format
+ order_amount - The final, total amount of the order. It should be the sum of line_item subtotals, shipping_subtotal, and tax_subtotal
+ transaction_id - The transaction id from the payment gateway for the credit card transaction
+ transaction_amount - The amount charged in the payment gateway for the credit card transaction.
+ card_type - The card network of the card used in the transaction. If not passed, Chargeback will ascertain based on the card number
+ card_prefix - The first six digits of the card number. Alternatively, use the card_number field.
+ card_suffix - The last four digits of the card number. Alternatively, use the card_number field.
+ card_number - If you use this field, you must pass the PAN in a masked format. Chargeback will extract the prefix and suffix.
+ card_exp - The expiration date captured at time of sale
+ reported_avs_status - If captured, the AVS status of the transaction
+ reported_cvv_status - If captured, the CVV status of the transaction
+ currency_code - Defaults to USD, please use ISO 4217
+ ip_address - The IP used by the cardholder to place the order in the merchant's sales platform
+ authorization_code - If captured, the authorization code returned by the payment gateway
+ arn - The ARN, if known
+ shipping_subtotal - The total amount charged for shipping.
+ tax_subtotal - The total amount charged for tax
+ source_url - The url to access this order in the merchant's sales platform.
+ tracking_numbers - Comma-separated list of tracking numbers; each will generate new shipment objects. See shipment actions.
+ customer_email - email from the customer profile
+ customer_first_name - first name from the customer profile
+ customer_last_name - last name from the customer profile
+ customer_phone - phone number from the customer profile
+ billing_first_name - the billing first name used in this particular order
+ billing_last_name - the billing last name used in this particular order
+ billing_address1 - the billing address used in this particular order
+ billing_address2 - the billing address line 2 used in this particular order
+ billing_city - the billing city used in this particular order
+ billing_state - the billing state used in this particular order
+ billing_country - the billing country used in this particular order
+ billing_postal - the billing postal code used in this particular order
+ id - CB system field for unique identifier for this order (maybe used for updates)
+ avs_status - CB system field for normalized version of the reported_avs_status, if recognized
+ cvv_status - CB system field for normalized version of the reported_cvv_status, if recognized
+ created_at - CB system field for the time in UTC when the order record was originally added to the database
+ updated_at - CB system field for the last time in UTC when the order record was modified
+ creator_id - CB system field for the id of the creator of the record. For API calls, it will be the user record that authorized the call
+ creator_type - CB system field for the type of creator of the record. For API calls, it will be the string 'User'
+ manually_generated - CB system field for identifying records created manually in the web UI
+ line_items - an array of line items
    + product_name - The name of the product sold, as it stood at the time of the order.
    + product_description - The description of the product, as it stood at the time of the order.
    + product_amount - The price of the product at the time of the order.
    + quantity - The number of this line item sold.
    + subtotal - Should be equal to quantity * subtotal. Can be computed from these if left blank.
    + source_product_id - The unique identifier of the product in the source system's backend database
+ shipments - an array of shipping tracking information. In most cases, the array will be auto-populated by shipper integrations if tracking_numbers are passed. If you know the shipper is unsupported by Chargeback's platform, you may pass additional keys to provide correct shipment information.
    + id - The Chargeback internal unique identifier for this shipment
    + tracking_number - The tracking number provided by the shipping partner to identify the shipment.
    + shipped_ts - The date the shipment was sent.
    + tracking_summary - A description from the shipping partner about the shipment.
    + source_url - When available, the URL of the shipment at the shipping partner website
    + origin_name - Identifying information about the sender
    + origin_address1 - Identifying information about the sender
    + origin_address2 - Identifying information about the sender
    + origin_city - Identifying information about the sender
    + origin_state - Identifying information about the sender
    + origin_country - Identifying information about the sender
    + origin_zip - Identifying information about the sender
    + destination_name - Identifying information about the recipient
    + destination_address1 - Identifying information about the recipient
    + destination_address2 - Identifying information about the recipient
    + destination_city - Identifying information about the recipient
    + destination_state - Identifying information about the recipient
    + destination_country - Identifying information about the recipient
    + destination_zip - Identifying information about the recipient
    + status - Additional field available from some shipping partners
    + status_code - Additional field available from some shipping partners
    + status_description - Additional field available from some shipping partners
    + scheduled_delivery_date - Additional field available from some shipping partners
    + actual_delivery_date - Additional field available from some shipping partners
    + attempted_delivery_date - Additional field available from some shipping partners
    + weight - Additional field available from some shipping partners
    + left_at - Additional field available from some shipping partners
    + service - Additional field available from some shipping partners
    + dimensions - Additional field available from some shipping partners
    + packaging - Additional field available from some shipping partners
    + packaging_count - Additional field available from some shipping partners
    + purchase_order_number - Additional field available from some shipping partners
    + invoice_number - Additional field available from some shipping partners
    + reference - Additional field available from some shipping partners
    + shipper_id - CB identifier for the shipping partner.
    + shipper_name

### Create a New Order [POST]

You may report a completed Order using this action. It takes a JSON object.

+ Request (application/json)

        {
            'crm_id : 444,
            'merchant_id' : 12345,
            'order_id' : 'abc123',
            'order_ts' : '2017-11-27T23:59:26Z'
            'order_amount' : '177.16',
            'transaction_id' : 'qwertyzzz',
            'transaction_amount' : '55.00',
            'card_prefix' : '444321',
            'card_suffix' : '8215',
            'card_exp' : '05/21',
            'reported_avs_status' : 'Y',
            'reported_cvv_status' : 'M',
            'ip_address' : '172.98.44.123',
            'authorization_code' : 'xxyyzz',
            'shipping_subtotal' : '5.00',
            'tax_subtotal' : '5.00',
            'source_url' : 'https://my-magento-site.com/admin-area/order-search.php?order_id=abc123',
            'tracking_numbers' : '1ZY2F2150255600110',
            'line_items' : [
                {
                    'product_name' : 'MIRRORLESS MICRO FOUR THIRDS 45-150 MM',
                    'product_description' : 'PANASONIC LUMIX G VARIO LENS, 45-150MM, F4.0-5.6 ASPH., MIRRORLESS MICRO FOUR THIRDS, MEGA OPTICAL I.S., H-FS45150AK (USA BLACK)',
                    'product_amount' : '147.99',
                    'quantity' : 1,
                    'subtotal' : '147.99',
                    'source_product_id' : 'prod-123'
                },
                {
                    'product_name' : 'Lens Cap',
                    'product_description' : 'Lens cap with lanyard fits most panasonic lumix cameras',
                    'product_amount' : '5.99',
                    'quantity' : 2,
                    'subtotal' : '11.98',
                    'source_product_id' : 'prod-777'
                }
            ],
            'shipping_subtotal' : '5.99',
            'tax_subtotal' : '11.20',
            'billing_first_name' : 'Nate',
            'billing_last_name' : 'Smith',
            'billing_address1' : '12345 My Actual House',
            'billing_city' : 'South Jordan',
            'billing_state' : 'UT',
            'billing_country' : 'USA',
            'billing_postal' : '84009',
        }

+ Response 201 (application/json)

    + Headers

            Location: orders/12345678.json

    + Body
            {
                'id' : '12345678',
                'avs_status' : 'Y',
                'cvv_status' : 'M',
                'created_at' : '2017-11-28T00:01:42Z',
                'updated_at' : '2017-11-28T00:01:42Z',
                'creator_id' : '55555',
                'creator_type' : 'User',
                'manually_generated' : false,
                'shipments' : [
                    {
                        'tracking_number' : '1ZY2F2150255600110',
                        'tracking_summary': null,
                        'shipper_name' : 'UPS',
                        'shipped_ts' : null,
                        'origin_name' : 'Cameras R Us',
                        'origin_address1' : '555 A Texas Road',
                        'origin_city' : 'Austin',
                        'origin_state' : 'TX',
                        'origin_country' : 'USA',
                        'origin_zip' : '73301',
                        'destination_first_name' : 'Nate'
                        'destination_last_name' : 'Smith',
                        'destination_address1' : '10235 S. Jordan Gateway',
                        'destination_address2' : 'Suite 500',
                        'destination_city' : 'South Jordan',
                        'destination_state' : 'UT',
                        'destination_country' : 'USA',
                        'destination_zip' : '84095',
                    }
                ],
                'crm_id' : 444,
                'merchant_id' : 12345,
                'order_id' : 'abc123',
                'order_ts' : '2017-11-27T23:59:26Z'
                'order_amount' : '177.16',
                'transaction_id' : 'qwertyzzz',
                'transaction_amount' : '55.00',
                'card_prefix' : '444321',
                'card_suffix' : '8215',
                'card_exp' : '05/21',
                'reported_avs_status' : 'Y',
                'reported_cvv_status' : 'M',
                'ip_address' : '172.98.44.123',
                'authorization_code' : 'xxyyzz',
                'shipping_subtotal' : '5.00',
                'tax_subtotal' : '5.00',
                'source_url' : 'https://my-magento-site.com/admin-area/order-search.php?order_id=abc123',
                'tracking_numbers' : '1ZY2F2150255600110',
                'line_items' : [
                    {
                        'product_name' : 'MIRRORLESS MICRO FOUR THIRDS 45-150 MM',
                        'product_description' : 'PANASONIC LUMIX G VARIO LENS, 45-150MM, F4.0-5.6 ASPH., MIRRORLESS MICRO FOUR THIRDS, MEGA OPTICAL I.S., H-FS45150AK (USA BLACK)',
                        'product_amount' : '147.99',
                        'quantity' : 1,
                        'subtotal' : '147.99',
                        'source_product_id' : 'prod-123'
                    },
                    {
                        'product_name' : 'Lens Cap',
                        'product_description' : 'Lens cap with lanyard fits most panasonic lumix cameras',
                        'product_amount' : '5.99',
                        'quantity' : 2,
                        'subtotal' : '11.98',
                        'source_product_id' : 'prod-777'
                    }
                ],
                'shipping_subtotal' : '5.99',
                'tax_subtotal' : '11.20',
                'billing_first_name' : 'Nate',
                'billing_last_name' : 'Smith',
                'billing_address1' : '12345 My Actual House',
                'billing_city' : 'South Jordan',
                'billing_state' : 'UT',
                'billing_country' : 'USA',
                'billing_postal' : '84009',
            }

### Search / List Orders [GET]

You may search existing orders that your api user is authorized to view.

TODO: More information here about search keys, pagination, and some request / response examples.


## Group Single Order

View and update single orders

## Order [/orders/12345678.json]

### Show an existing Order [GET]

You may view an existing Order record and its details.

### Update an existing Order [PUT]

You may update information about an Order already reported to Chargeback using this action. You must specify the Order based on Chargeback's unique identifier (id) for the Order.

+ Request (application/json)
    {
        'id' : 12345678,
        'billing_address1' : '12345 a different address',
        'billing_city' : 'Another City',
        'billing_state' : 'CA',
        'billing_country' : 'USA',
        'billing_postal' : '90233'
    }
+ Response 201 (application/json)

    + Headers

            Location: orders/12345678.json

    + Body
        {
            'id' : '12345678',
            'etc' : '...'
        }
### Submit (create or update) an Order [PUT]

You may create or update orders based on the unique identifiers (crm_id, merchant_id, order_id) of the order. If such a record already exists, it will be updated. Otherwise, a new record will be created.

+ Request (application/json)
    {
        'crm_id' : 777,
        'merchant_id' : 8888,
        'order_id' : 'abcdef54321',
        'etc': '...'
    }
+ Response 201 (application/json)

    + Headers

            Location: orders/55555.json

    + Body
        {
            'id' : 55555,
            'etc' : '...'
        }
## Group Transactions

## Transaction [/transactions.json]

A Transaction object represents a single credit card transaction in the payment gateway.

## Group Disputes

## Dispute [/disputes.json]

A Dispute is a retrieval request, chargeback, or pre_arbitration / second chargeback reported by the payment processor.

## Group Alerts

## Alert [/alerts.json]

An Alert notifies of a pending chargeback.

## Group Mids

## Mid [/mids.json]

The MID, or Merchant ID, is an identifier for the merchant account. Since larger merchants often use many MIDs, you can use the MID endpoints to keep Chargeback up-to-date with the MIDs you are using.
